# Generated by Django 3.2.5 on 2021-07-27 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=15, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=15, unique=True)),
                ('list_order', models.IntegerField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.board')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('card_order', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.board')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.list')),
            ],
        ),
    ]
